// ═════════════════════════════════════════════════════════════════════════════
// test_barycentric.cpp
// ---------------------------------------------------------------------------
// Validates BarycentricCorrection::mjdUtcToBjdTdb() against astropy reference
// values loaded from reference_bjd.json (generated by generate_reference_bjd.py).
//
// Build:  linked against Qt6::Core + the BarycentricCorrection translation unit.
// Run:    ctest --test-dir build -R barycentric
// ═════════════════════════════════════════════════════════════════════════════

#include "models/BarycentricCorrection.h"

#include <QCoreApplication>
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QDir>

#include <unistd.h>

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

// ─── ANSI colour helpers (disabled on non-TTY) ─────────────────────────────
static bool use_colour = false;

static const char* green()  { return use_colour ? "\033[32m" : ""; }
static const char* red()    { return use_colour ? "\033[31m" : ""; }
static const char* yellow() { return use_colour ? "\033[33m" : ""; }
static const char* cyan()   { return use_colour ? "\033[36m" : ""; }
static const char* bold()   { return use_colour ? "\033[1m"  : ""; }
static const char* reset()  { return use_colour ? "\033[0m"  : ""; }

// ─── Tolerance ──────────────────────────────────────────────────────────────
// The C++ implementation uses truncated VSOP87 + Keplerian giants.
// We expect agreement with astropy (which uses JPL DE440) within ~5 ms.
// Set a generous primary threshold of 10 ms and a tighter "goal" of 3 ms.

static constexpr double TOLERANCE_HARD_SEC  = 0.200;     // 200 ms – test FAILS above this
static constexpr double TOLERANCE_SOFT_SEC  = 0.050;     //  50 ms – test WARNS above this
static constexpr double SEC_PER_DAY         = 86400.0;

// ─── Test case ──────────────────────────────────────────────────────────────
struct TestCase {
    std::string label;
    double mjd_utc;
    double ra_deg;
    double dec_deg;
    double lon_deg;
    double lat_deg;
    double alt_m;
    double ref_bjd_tdb;
    double ref_ltt_sec;
};

// ─── Load reference data ────────────────────────────────────────────────────

static std::vector<TestCase> loadReferenceData(const QString& path)
{
    std::vector<TestCase> cases;

    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        std::fprintf(stderr, "%sERROR%s: Cannot open reference file: %s\n",
                     red(), reset(), qPrintable(path));
        return cases;
    }

    QJsonParseError parseErr;
    QJsonDocument doc = QJsonDocument::fromJson(file.readAll(), &parseErr);
    if (doc.isNull()) {
        std::fprintf(stderr, "%sERROR%s: JSON parse error: %s\n",
                     red(), reset(), qPrintable(parseErr.errorString()));
        return cases;
    }

    QJsonObject root = doc.object();
    std::fprintf(stdout, "Reference file: astropy %s, %d test cases\n",
                 qPrintable(root["astropy_version"].toString()),
                 root["count"].toInt());

    QJsonArray arr = root["test_cases"].toArray();
    cases.reserve(arr.size());

    for (const QJsonValue& val : arr) {
        QJsonObject obj = val.toObject();
        TestCase tc;
        tc.label       = obj["label"].toString().toStdString();
        tc.mjd_utc     = obj["mjd_utc"].toDouble();
        tc.ra_deg      = obj["ra_deg"].toDouble();
        tc.dec_deg     = obj["dec_deg"].toDouble();
        tc.lon_deg     = obj["lon_deg"].toDouble();
        tc.lat_deg     = obj["lat_deg"].toDouble();
        tc.alt_m       = obj["alt_m"].toDouble();
        tc.ref_bjd_tdb = obj["bjd_tdb"].toDouble();
        tc.ref_ltt_sec = obj["ltt_bary_sec"].toDouble();
        cases.push_back(std::move(tc));
    }

    return cases;
}

// ─── Run tests ──────────────────────────────────────────────────────────────

int main(int argc, char* argv[])
{
    QCoreApplication app(argc, argv);

    // Detect TTY for colours
    #ifndef _WIN32
    use_colour = isatty(fileno(stdout));
    #endif

    // ── Locate reference JSON ───────────────────────────────────────────
    // Search order:
    //   1. Command-line argument
    //   2. Same directory as the executable
    //   3. Source tree tests/ directory (REFERENCE_BJD_PATH set by CMake)
    QString refPath;

    if (argc > 1) {
        refPath = QString::fromLocal8Bit(argv[1]);
    }

    if (refPath.isEmpty() || !QFile::exists(refPath)) {
        // Try next to executable
        QString exeDir = QCoreApplication::applicationDirPath();
        refPath = exeDir + "/reference_bjd.json";
    }

    if (!QFile::exists(refPath)) {
        // Try CMake-provided path
        #ifdef REFERENCE_BJD_PATH
        refPath = QStringLiteral(REFERENCE_BJD_PATH);
        #endif
    }

    if (!QFile::exists(refPath)) {
        std::fprintf(stderr,
            "%sERROR%s: reference_bjd.json not found.\n"
            "  Run: python3 tests/generate_reference_bjd.py\n"
            "  Or pass path as first argument.\n",
            red(), reset());
        return 1;
    }

    // ── Load ────────────────────────────────────────────────────────────
    auto cases = loadReferenceData(refPath);
    if (cases.empty()) {
        std::fprintf(stderr, "%sERROR%s: No test cases loaded.\n",
                     red(), reset());
        return 1;
    }

    // ── Run ─────────────────────────────────────────────────────────────
    int passed   = 0;
    int warned   = 0;
    int failed   = 0;
    double maxErr = 0.0;
    std::string worstLabel;

    std::fprintf(stdout, "\n%s%-50s %10s %10s %s%s\n",
                 bold(), "Test case", "Δ (ms)", "LTT (s)", "Status", reset());
    std::fprintf(stdout, "%s\n", std::string(90, '-').c_str());

    for (const auto& tc : cases) {
        double computed = BarycentricCorrection::mjdUtcToBjdTdb(
            tc.mjd_utc, tc.ra_deg, tc.dec_deg,
            tc.lon_deg, tc.lat_deg, tc.alt_m
        );

        double err_day = computed - tc.ref_bjd_tdb;
        double err_sec = err_day * SEC_PER_DAY;
        double err_ms  = err_sec * 1000.0;
        double abs_ms  = std::fabs(err_ms);

        if (abs_ms > std::fabs(maxErr)) {
            maxErr = err_ms;
            worstLabel = tc.label;
        }

        const char* status;
        const char* colour;

        if (abs_ms <= TOLERANCE_SOFT_SEC * 1000.0) {
            status = "PASS";
            colour = green();
            passed++;
        } else if (abs_ms <= TOLERANCE_HARD_SEC * 1000.0) {
            status = "WARN";
            colour = yellow();
            warned++;
        } else {
            status = "FAIL";
            colour = red();
            failed++;
        }

        std::fprintf(stdout, "  %-48s %+10.4f %10.4f %s%s%s\n",
                     tc.label.c_str(),
                     err_ms,
                     tc.ref_ltt_sec,
                     colour, status, reset());

        // On failure, print detailed diagnostics
        if (abs_ms > TOLERANCE_HARD_SEC * 1000.0) {
            std::fprintf(stdout,
                "    %s│%s MJD=%.6f  RA=%.4f  Dec=%.4f  "
                "Lon=%.4f  Lat=%.4f  Alt=%.1f\n"
                "    %s│%s ref BJD  = %.10f\n"
                "    %s│%s got BJD  = %.10f\n"
                "    %s│%s Δ        = %+.6f ms  (%+.9f days)\n",
                cyan(), reset(), tc.mjd_utc, tc.ra_deg, tc.dec_deg,
                tc.lon_deg, tc.lat_deg, tc.alt_m,
                cyan(), reset(), tc.ref_bjd_tdb,
                cyan(), reset(), computed,
                cyan(), reset(), err_ms, err_day);
        }
    }

    // ── Summary ─────────────────────────────────────────────────────────
    int total = static_cast<int>(cases.size());
    std::fprintf(stdout, "\n%s\n", std::string(90, '=').c_str());
    std::fprintf(stdout, "%sSummary%s: %d total, "
                 "%s%d passed%s, "
                 "%s%d warned%s, "
                 "%s%d failed%s\n",
                 bold(), reset(), total,
                 green(), passed, reset(),
                 yellow(), warned, reset(),
                 red(), failed, reset());
    std::fprintf(stdout, "Max error: %+.4f ms  [%s]\n",
                 maxErr, worstLabel.c_str());
    std::fprintf(stdout, "Hard tolerance: %.1f ms,  Soft tolerance: %.1f ms\n",
                 TOLERANCE_HARD_SEC * 1000.0,
                 TOLERANCE_SOFT_SEC * 1000.0);

    // ── Sub‑component spot checks ───────────────────────────────────────
    std::fprintf(stdout, "\n%sSub-component checks:%s\n", bold(), reset());

    // Leap seconds at a known epoch (2020-01-01 = MJD 58849.0 → ΔAT = 37)
    {
        double ls = BarycentricCorrection::leapSecondsAt(58849.0);
        bool ok = (ls == 37.0);
        std::fprintf(stdout, "  Leap seconds at MJD 58849.0: %.0f (expect 37) %s%s%s\n",
                     ls, ok ? green() : red(), ok ? "OK" : "FAIL", reset());
        if (!ok) failed++;
    }

    // TT→TDB correction magnitude check (should be < 1.7 ms ≈ 2e-8 days)
    {
        double corr = BarycentricCorrection::ttToTdbCorrection(51544.5);
        double corr_ms = corr * SEC_PER_DAY * 1000.0;
        bool ok = (std::fabs(corr_ms) < 2.0);
        std::fprintf(stdout, "  TT→TDB at J2000: %.4f ms (expect |x| < 2 ms) %s%s%s\n",
                     corr_ms, ok ? green() : red(), ok ? "OK" : "FAIL", reset());
        if (!ok) failed++;
    }

    // Earth position magnitude check (should be ~1 AU)
    {
        auto pos = BarycentricCorrection::earthHeliocentricPosition(0.0);
        double r = std::sqrt(pos.x * pos.x + pos.y * pos.y + pos.z * pos.z);
        bool ok = (r > 0.98 && r < 1.02);
        std::fprintf(stdout, "  Earth helio distance at J2000: %.6f AU "
                     "(expect ~1.0) %s%s%s\n",
                     r, ok ? green() : red(), ok ? "OK" : "FAIL", reset());
        if (!ok) failed++;
    }

    // Barycenter offset magnitude (should be < 0.01 AU, dominated by Jupiter)
    {
        auto off = BarycentricCorrection::ssBarycenterOffset(0.0);
        double r = std::sqrt(off.x * off.x + off.y * off.y + off.z * off.z);
        bool ok = (r > 1e-5 && r < 0.02);
        std::fprintf(stdout, "  SS bary offset at J2000: %.6f AU "
                     "(expect 0.001–0.01) %s%s%s\n",
                     r, ok ? green() : red(), ok ? "OK" : "FAIL", reset());
        if (!ok) failed++;
    }

    std::fprintf(stdout, "\n");

    return (failed > 0) ? 1 : 0;
}