#include "IsisEnvironment.h"

#include "AppPaths.h"
#include "AppSettings.h"

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QStandardPaths>
#include <QTextStream>

#ifndef ASTRA_ISIS_BUNDLE_RELDIR
#  define ASTRA_ISIS_BUNDLE_RELDIR ""
#endif
#ifndef ASTRA_ISIS_SOURCE_DIR
#  define ASTRA_ISIS_SOURCE_DIR ""
#endif

namespace {
// A bundle is valid if it has the ISIS_SRCDIR subtree we point ISIS at. The
// AppImage build stages the versioned isis/<ver> tree under a fixed "srcdir"
// so this stays version-agnostic.
bool looksLikeBundle(const QString& root)
{
    return !root.isEmpty()
        && QFileInfo(root + "/srcdir/etc").isDir();
}
} // namespace

QString IsisEnvironment::bundleRoot()
{
    const QString appDir = QCoreApplication::applicationDirPath();

    // 1. Prefix-relative bundle baked at configure time (AppImage / install).
    {
        const QString rel = QStringLiteral(ASTRA_ISIS_BUNDLE_RELDIR);
        if (!rel.isEmpty()) {
            const QString cand = QDir(appDir).absoluteFilePath(rel);
            if (looksLikeBundle(cand))
                return QDir(cand).absolutePath();
        }
    }
    // 2. Configure-time source dir (dev convenience; e.g. an external prefix).
    {
        const QString src = QStringLiteral(ASTRA_ISIS_SOURCE_DIR);
        if (looksLikeBundle(src))
            return QDir(src).absolutePath();
    }
    return {};
}

bool IsisEnvironment::bundleAvailable()
{
    return !bundleRoot().isEmpty();
}

QString IsisEnvironment::bundledBinary()
{
    // The AppImage build feeds the isis binary to linuxdeploy, which drops it
    // next to the ASTRA executable (usr/bin) with its libs bundled.
    const QString cand =
        QDir(QCoreApplication::applicationDirPath()).absoluteFilePath(QStringLiteral("isis"));
    QFileInfo fi(cand);
    if (fi.exists() && fi.isExecutable())
        return fi.absoluteFilePath();

    // Fallback: a binary inside the bundle tree itself.
    const QString root = bundleRoot();
    if (!root.isEmpty()) {
        QFileInfo bi(root + "/bin/isis");
        if (bi.exists() && bi.isExecutable())
            return bi.absoluteFilePath();
    }
    return {};
}

bool IsisEnvironment::isBundled(const QString& binaryPath)
{
    if (binaryPath.isEmpty()) return false;
    const QString resolved = QFileInfo(binaryPath).absoluteFilePath();

    if (const QString b = bundledBinary();
        !b.isEmpty() && QFileInfo(b).absoluteFilePath() == resolved)
        return true;

    const QString root = bundleRoot();
    return !root.isEmpty()
        && resolved.startsWith(QDir(root).absolutePath() + '/');
}

QString IsisEnvironment::resolveBinary()
{
    AppSettings settings;
    const QString custom = settings.isisBinaryPath().trimmed();
    if (!custom.isEmpty() && QFileInfo(custom).isExecutable())
        return custom;

    if (const QString b = bundledBinary(); !b.isEmpty())
        return b;

    return QStandardPaths::findExecutable(QStringLiteral("isis"));
}

QString IsisEnvironment::privateHome()
{
    return QDir(AppPaths::root()).absoluteFilePath(QStringLiteral("isis-home"));
}

void IsisEnvironment::writeIsisrc(const QString& root)
{
    const QString home = privateHome();
    QDir().mkpath(home);

    QFile f(home + "/.isisrc");
    if (!f.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text))
        return;
    QTextStream o(&f);
    // Mirror the user's hand-written ~/.isisrc, but point at the bundled dirs
    // (absolute paths recomputed for the current mount).
    o << "% Generated by ASTRA for the bundled ISIS - do not edit.\n";
    o << "add_to_isis_load_path(\"" << root << "/share/slsh/local-packages\");\n";
    o << "add_to_isis_load_path(\"" << root << "/isisscripts/share\");\n";
    o << "add_to_isis_load_path(\"" << root << "/stellar_isisscripts/share\");\n";
    o << "define ris() { require(\"isisscripts\"); };\n";
    o << "define rmy() { require(\"stellar_isisscripts\"); };\n";
}

QProcessEnvironment IsisEnvironment::environmentFor(const QString& binaryPath)
{
    QProcessEnvironment env = QProcessEnvironment::systemEnvironment();
    if (!isBundled(binaryPath))
        return env;   // user-provided isis: leave their environment untouched

    const QString root   = bundleRoot();
    const QString appDir = QCoreApplication::applicationDirPath();
    const QString libDir = QDir(appDir).absoluteFilePath(QStringLiteral("../lib"));
    if (root.isEmpty())
        return env;

    writeIsisrc(root);

    auto prepend = [&env](const QString& key, const QStringList& dirs) {
        QStringList parts = dirs;
        const QString existing = env.value(key);
        if (!existing.isEmpty()) parts << existing;
        env.insert(key, parts.join(':'));
    };

    env.insert(QStringLiteral("ISIS_SRCDIR"),       root + "/srcdir");
    env.insert(QStringLiteral("SLSH_PATH"),         root + "/share/slsh");
    env.insert(QStringLiteral("SLANG_MODULE_PATH"), root + "/lib/slang/v2/modules");
    env.insert(QStringLiteral("HOME"),              privateHome());
    // PGPLOT looks up its font here; bundled under <root>/pgplot by the build.
    env.insert(QStringLiteral("PGPLOT_DIR"),  root + "/pgplot");
    env.insert(QStringLiteral("PGPLOT_FONT"), root + "/pgplot/grfont.dat");
    prepend(QStringLiteral("LD_LIBRARY_PATH"),
            { QDir(libDir).absolutePath(), root + "/lib" });
    prepend(QStringLiteral("PATH"), { appDir, root + "/bin" });
    return env;
}
